
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { readFileSync } from "node:fs";
import { defineConfig } from "prisma/config";

// Each database provider needs its own SQL migration history.
const schema = readFileSync(new URL("./src/prisma/schema.prisma", import.meta.url), "utf8");
const provider = schema.match(/datasource\s+db\s*\{[^}]*provider\s*=\s*"([^"]+)"/)?.[1];
if (provider !== "sqlite" && provider !== "postgresql") {
  throw new Error("Unsupported Prisma datasource provider");
}

export default defineConfig({
  earlyAccess: true,
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: provider === "postgresql" ? "src/prisma/migrations-postgresql" : "src/prisma/migrations",
  },
});
